apiVersion: v1
kind: Service
metadata:
  name: webhook-scanner
  namespace: webhook-scanner
  labels:
    app.kubernetes.io/name: registry-webhook-scanner
    app.kubernetes.io/component: scanner
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: registry-webhook-scanner
    app.kubernetes.io/component: scanner
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
